package org.tbc.content.compile;

import org.tbc.content.dbc.DbcBinding;
import org.tbc.content.dbc.WdbcFile;
import org.tbc.content.domain.ContentDomain;
import org.tbc.content.domain.SpellDomain;
import org.tbc.content.mpq.MpqWriter;
import org.tbc.content.util.Backup;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/** YAML deltas → merged DBC + SQL + patch MPQ. */
public final class ContentCompiler {
    private final Map<String, ContentDomain> domains;

    public ContentCompiler() {
        this.domains = new LinkedHashMap<>();
        register(new SpellDomain());
    }

    public void register(ContentDomain domain) {
        domains.put(domain.kind().toLowerCase(Locale.ROOT), domain);
    }

    public CompileResult compile(Path contentRoot, Path baseDbcDir, Path outDir, String mpqName)
            throws IOException {
        Path bindingsDir = contentRoot.resolve("bindings").resolve("tbc243");
        Map<String, DbcBinding> bindings = DbcBinding.loadDirectory(bindingsDir);
        if (bindings.isEmpty()) {
            throw new IOException("no bindings in " + bindingsDir);
        }
        Files.createDirectories(outDir);
        CompileContext ctx = new CompileContext(baseDbcDir, outDir, bindings);
        List<ContentDelta> deltas = YamlDeltaLoader.loadTree(contentRoot);
        if (deltas.isEmpty()) {
            throw new IOException("no YAML deltas under " + contentRoot);
        }
        for (ContentDelta d : deltas) {
            ContentDomain domain = domains.get(d.kind().toLowerCase(Locale.ROOT));
            if (domain == null) {
                throw new IllegalArgumentException(d.source() + ": unknown kind '" + d.kind()
                        + "' (known: " + domains.keySet() + ")");
            }
            domain.apply(d, ctx);
        }
        SpellDomain.finish(ctx);

        Path dbcOut = outDir.resolve("dbc");
        Files.createDirectories(dbcOut);
        List<Path> dbcFiles = new java.util.ArrayList<>();
        for (String name : ctx.touchedDbcs()) {
            WdbcFile dbc = ctx.requireDbc(name);
            Path target = dbcOut.resolve(name + ".dbc");
            Backup.bakIfExists(target);
            dbc.save(target);
            dbcFiles.add(target);
        }

        Path sqlFile = outDir.resolve("spell_template_patch.sql");
        Backup.bakIfExists(sqlFile);
        StringBuilder sql = new StringBuilder();
        sql.append("-- generated by tbc-content; apply to tbcmangos\n");
        for (String stmt : ctx.sqlStatements()) {
            sql.append(stmt).append('\n');
        }
        Files.writeString(sqlFile, sql.toString(), StandardCharsets.UTF_8);

        Path mpqPath = outDir.resolve(mpqName);
        Backup.bakIfExists(mpqPath);
        Map<String, Path> mpqEntries = new LinkedHashMap<>();
        for (Path dbcFile : dbcFiles) {
            mpqEntries.put("DBFilesClient\\" + dbcFile.getFileName(), dbcFile);
        }
        MpqWriter.create(mpqPath, mpqEntries);

        return new CompileResult(dbcFiles, sqlFile, mpqPath, deltas.size(), ctx.sqlStatements().size());
    }

    public record CompileResult(List<Path> dbcFiles, Path sqlFile, Path mpqFile, int deltas, int sqlCount) {}
}
