package org.tbc.matrix;

import org.tbc.world.net.wow8606.Opcodes;

import java.util.Set;

/** Opcodes with a dedicated branch in WorldSession.handle (including Handle_NULL-style early returns). */
final class HandledOpcodes {
    private HandledOpcodes() {}

    static final Set<Integer> SET = Set.of(
            Opcodes.CMSG_WARDEN_DATA,
            Opcodes.CMSG_PING,
            Opcodes.CMSG_AUTH_SESSION,
            Opcodes.CMSG_CHAR_ENUM,
            Opcodes.CMSG_CHAR_CREATE,
            Opcodes.CMSG_CHAR_DELETE,
            Opcodes.CMSG_PLAYER_LOGIN,
            Opcodes.MSG_MOVE_WORLDPORT_ACK,
            Opcodes.CMSG_FORCE_MOVE_ROOT_ACK,
            Opcodes.CMSG_FORCE_MOVE_UNROOT_ACK,
            Opcodes.CMSG_LOGOUT_REQUEST,
            Opcodes.CMSG_LOGOUT_CANCEL,
            Opcodes.CMSG_PLAYER_LOGOUT,
            Opcodes.CMSG_MESSAGECHAT,
            Opcodes.CMSG_NAME_QUERY,
            Opcodes.CMSG_PET_NAME_QUERY,
            Opcodes.CMSG_GUILD_QUERY,
            Opcodes.CMSG_ITEM_QUERY_SINGLE,
            Opcodes.CMSG_PAGE_TEXT_QUERY,
            Opcodes.CMSG_QUEST_QUERY,
            Opcodes.CMSG_GAMEOBJECT_QUERY,
            Opcodes.CMSG_CREATURE_QUERY,
            Opcodes.CMSG_WHOIS,
            Opcodes.CMSG_QUERY_TIME,
            Opcodes.CMSG_TIME_SYNC_RESP,
            Opcodes.CMSG_SET_ACTIVE_MOVER,
            Opcodes.CMSG_ZONEUPDATE,
            Opcodes.CMSG_CONTACT_LIST,
            Opcodes.CMSG_SET_ACTION_BUTTON,
            Opcodes.CMSG_TUTORIAL_FLAG,
            Opcodes.CMSG_NEXT_CINEMATIC_CAMERA,
            Opcodes.CMSG_COMPLETE_CINEMATIC,
            Opcodes.CMSG_ATTACKSWING,
            Opcodes.CMSG_ATTACKSTOP,
            Opcodes.CMSG_SETSHEATHED,
            Opcodes.CMSG_SET_SELECTION,
            Opcodes.CMSG_LOOT,
            Opcodes.CMSG_LOOT_MONEY,
            Opcodes.CMSG_LOOT_RELEASE,
            Opcodes.CMSG_CAST_SPELL,
            Opcodes.CMSG_GOSSIP_HELLO,
            Opcodes.CMSG_QUESTGIVER_HELLO,
            Opcodes.CMSG_QUESTGIVER_QUERY_QUEST,
            Opcodes.CMSG_QUESTGIVER_ACCEPT_QUEST,
            Opcodes.CMSG_QUESTGIVER_COMPLETE_QUEST,
            Opcodes.CMSG_QUESTGIVER_CHOOSE_REWARD,
            Opcodes.CMSG_LIST_INVENTORY,
            Opcodes.CMSG_GROUP_INVITE,
            Opcodes.CMSG_GROUP_ACCEPT,
            Opcodes.CMSG_GROUP_DISBAND,
            Opcodes.CMSG_INITIATE_TRADE,
            Opcodes.CMSG_BEGIN_TRADE,
            Opcodes.CMSG_SET_TRADE_ITEM,
            Opcodes.CMSG_ACCEPT_TRADE,
            Opcodes.CMSG_CANCEL_TRADE,
            Opcodes.CMSG_WHO,
            Opcodes.CMSG_ADD_FRIEND,
            Opcodes.CMSG_SEND_MAIL,
            Opcodes.CMSG_GET_MAIL_LIST,
            Opcodes.CMSG_MAIL_TAKE_ITEM,
            Opcodes.MSG_AUCTION_HELLO,
            Opcodes.CMSG_BATTLEMASTER_JOIN,
            Opcodes.CMSG_BATTLEMASTER_JOIN_ARENA,
            Opcodes.CMSG_REPOP_REQUEST,
            Opcodes.CMSG_RECLAIM_CORPSE,
            Opcodes.CMSG_SELF_RES,
            Opcodes.CMSG_PET_ACTION,
            Opcodes.CMSG_JOIN_CHANNEL,
            Opcodes.CMSG_BUY_ITEM,
            Opcodes.CMSG_BUY_ITEM_IN_SLOT,
            Opcodes.CMSG_LEARN_TALENT,
            Opcodes.CMSG_TRAINER_LIST,
            Opcodes.CMSG_ACTIVATETAXI,
            Opcodes.CMSG_ACTIVATETAXIEXPRESS,
            Opcodes.CMSG_GAMEOBJ_USE,
            Opcodes.CMSG_GMTICKET_CREATE,
            Opcodes.CMSG_INSPECT,
            Opcodes.CMSG_DUEL_ACCEPTED,
            Opcodes.CMSG_TOGGLE_PVP,
            Opcodes.CMSG_OPEN_ITEM,
            Opcodes.CMSG_AREA_SPIRIT_HEALER_QUERY,
            Opcodes.CMSG_AREA_SPIRIT_HEALER_QUEUE,
            Opcodes.MSG_PVP_LOG_DATA,
            Opcodes.CMSG_VOICE_SESSION_ENABLE,
            Opcodes.CMSG_SWAP_INV_ITEM,
            Opcodes.CMSG_SWAP_ITEM,
            Opcodes.CMSG_DESTROYITEM,
            Opcodes.CMSG_AREATRIGGER,
            Opcodes.CMSG_RESET_INSTANCES,
            Opcodes.CMSG_BATTLEFIELD_PORT,
            Opcodes.CMSG_TRAINER_BUY_SPELL,
            Opcodes.CMSG_TEXT_EMOTE,
            Opcodes.CMSG_GROUP_RAID_CONVERT,
            Opcodes.CMSG_LOOT_METHOD,
            Opcodes.MSG_RAID_READY_CHECK,
            Opcodes.CMSG_GUILD_CREATE,
            Opcodes.CMSG_GUILD_BANKER_ACTIVATE,
            Opcodes.CMSG_GUILD_BANK_SWAP_ITEMS,
            Opcodes.CMSG_GUILD_BANK_BUY_TAB,
            Opcodes.CMSG_AUCTION_LIST_ITEMS,
            Opcodes.CMSG_SET_LOOKING_FOR_GROUP,
            Opcodes.MSG_LOOKING_FOR_GROUP,
            Opcodes.CMSG_STABLE_PET,
            Opcodes.CMSG_UNSTABLE_PET,
            Opcodes.CMSG_BUY_STABLE_SLOT,
            Opcodes.CMSG_SELL_ITEM,
            Opcodes.CMSG_BUYBACK_ITEM,
            Opcodes.CMSG_REPAIR_ITEM,
            Opcodes.CMSG_SOCKET_GEMS,
            Opcodes.MSG_RANDOM_ROLL,
            Opcodes.MSG_MINIMAP_PING,
            Opcodes.CMSG_REPORT_PVP_AFK,
            Opcodes.MSG_TALENT_WIPE_CONFIRM,
            Opcodes.CMSG_CANCEL_CHANNELLING,
            Opcodes.CMSG_FORCE_RUN_SPEED_CHANGE_ACK,
            Opcodes.CMSG_CANCEL_MOUNT_AURA,
            Opcodes.CMSG_PUSHQUESTTOPARTY,
            Opcodes.CMSG_LOOT_MASTER_GIVE,
            Opcodes.CMSG_LOOT_ROLL,
            Opcodes.CMSG_GMTICKET_GETTICKET,
            Opcodes.CMSG_ACCEPT_LFG_MATCH,
            Opcodes.CMSG_TURN_IN_PETITION,
            Opcodes.MSG_INSPECT_HONOR_STATS,
            Opcodes.CMSG_CHANNEL_LIST,
            Opcodes.CMSG_SPIRIT_HEALER_ACTIVATE,
            Opcodes.CMSG_TOTEM_DESTROYED,
            Opcodes.CMSG_PET_ABANDON
    );

    static boolean handled(int id) {
        if (id >= Opcodes.MSG_MOVE_START_FORWARD && id <= Opcodes.MSG_MOVE_HEARTBEAT) {
            return true;
        }
        return SET.contains(id);
    }
}
