package org.tbc.world.net.wow8606;

/** Generated from spec/03-protocol/update-fields.yaml. PLAYER_END is 1592. */
public final class UpdateFields {
    private UpdateFields() {}
    public static final int PUBLIC = 1;
    public static final int PRIVATE = 2;
    public static final int OWNER_ONLY = 4;
    public static final int GROUP_ONLY = 32;
    public static final int DYNAMIC = 64;
    public static final int OBJECT_END = 6;
    public static final int ITEM_END = 60;
    public static final int CONTAINER_END = 134;
    public static final int UNIT_END = 234;
    public static final int PLAYER_END = 1592;
    public static final int GAMEOBJECT_END = 26;
    public static final int DYNAMICOBJECT_END = 16;
    public static final int CORPSE_END = 40;
    public static final int OBJECT_FIELD_GUID = 0;
    public static final int OBJECT_FIELD_TYPE = 2;
    public static final int OBJECT_FIELD_ENTRY = 3;
    public static final int OBJECT_FIELD_SCALE_X = 4;
    public static final int OBJECT_FIELD_PADDING = 5;
    public static final int ITEM_FIELD_OWNER = 6;
    public static final int ITEM_FIELD_CONTAINED = 8;
    public static final int ITEM_FIELD_CREATOR = 10;
    public static final int ITEM_FIELD_GIFTCREATOR = 12;
    public static final int ITEM_FIELD_STACK_COUNT = 14;
    public static final int ITEM_FIELD_DURATION = 15;
    public static final int ITEM_FIELD_SPELL_CHARGES = 16;
    public static final int ITEM_FIELD_FLAGS = 21;
    public static final int ITEM_FIELD_ENCHANTMENT_1_1 = 22;
    public static final int ITEM_FIELD_PROPERTY_SEED = 55;
    public static final int ITEM_FIELD_RANDOM_PROPERTIES_ID = 56;
    public static final int ITEM_FIELD_ITEM_TEXT_ID = 57;
    public static final int ITEM_FIELD_DURABILITY = 58;
    public static final int ITEM_FIELD_MAXDURABILITY = 59;
    public static final int CONTAINER_FIELD_NUM_SLOTS = 60;
    public static final int CONTAINER_ALIGN_PAD = 61;
    public static final int CONTAINER_FIELD_SLOT_1 = 62;
    public static final int UNIT_FIELD_CHARM = 6;
    public static final int UNIT_FIELD_SUMMON = 8;
    public static final int UNIT_FIELD_CHARMEDBY = 10;
    public static final int UNIT_FIELD_SUMMONEDBY = 12;
    public static final int UNIT_FIELD_CREATEDBY = 14;
    public static final int UNIT_FIELD_TARGET = 16;
    public static final int UNIT_FIELD_PERSUADED = 18;
    public static final int UNIT_FIELD_CHANNEL_OBJECT = 20;
    public static final int UNIT_FIELD_HEALTH = 22;
    public static final int UNIT_FIELD_POWER1 = 23;
    public static final int UNIT_FIELD_POWER2 = 24;
    public static final int UNIT_FIELD_POWER3 = 25;
    public static final int UNIT_FIELD_POWER4 = 26;
    public static final int UNIT_FIELD_POWER5 = 27;
    public static final int UNIT_FIELD_MAXHEALTH = 28;
    public static final int UNIT_FIELD_MAXPOWER1 = 29;
    public static final int UNIT_FIELD_MAXPOWER2 = 30;
    public static final int UNIT_FIELD_MAXPOWER3 = 31;
    public static final int UNIT_FIELD_MAXPOWER4 = 32;
    public static final int UNIT_FIELD_MAXPOWER5 = 33;
    public static final int UNIT_FIELD_LEVEL = 34;
    public static final int UNIT_FIELD_FACTIONTEMPLATE = 35;
    public static final int UNIT_FIELD_BYTES_0 = 36;
    public static final int UNIT_VIRTUAL_ITEM_SLOT_DISPLAY = 37;
    public static final int UNIT_VIRTUAL_ITEM_INFO = 40;
    public static final int UNIT_FIELD_FLAGS = 46;
    public static final int UNIT_FIELD_FLAGS_2 = 47;
    public static final int UNIT_FIELD_AURA = 48;
    public static final int UNIT_FIELD_AURAFLAGS = 104;
    public static final int UNIT_FIELD_AURALEVELS = 118;
    public static final int UNIT_FIELD_AURAAPPLICATIONS = 132;
    public static final int UNIT_FIELD_AURASTATE = 146;
    public static final int UNIT_FIELD_BASEATTACKTIME = 147;
    public static final int UNIT_FIELD_RANGEDATTACKTIME = 149;
    public static final int UNIT_FIELD_BOUNDINGRADIUS = 150;
    public static final int UNIT_FIELD_COMBATREACH = 151;
    public static final int UNIT_FIELD_DISPLAYID = 152;
    public static final int UNIT_FIELD_NATIVEDISPLAYID = 153;
    public static final int UNIT_FIELD_MOUNTDISPLAYID = 154;
    public static final int UNIT_FIELD_MINDAMAGE = 155;
    public static final int UNIT_FIELD_MAXDAMAGE = 156;
    public static final int UNIT_FIELD_MINOFFHANDDAMAGE = 157;
    public static final int UNIT_FIELD_MAXOFFHANDDAMAGE = 158;
    public static final int UNIT_FIELD_BYTES_1 = 159;
    public static final int UNIT_FIELD_PETNUMBER = 160;
    public static final int UNIT_FIELD_PET_NAME_TIMESTAMP = 161;
    public static final int UNIT_FIELD_PETEXPERIENCE = 162;
    public static final int UNIT_FIELD_PETNEXTLEVELEXP = 163;
    public static final int UNIT_DYNAMIC_FLAGS = 164;
    public static final int UNIT_CHANNEL_SPELL = 165;
    public static final int UNIT_MOD_CAST_SPEED = 166;
    public static final int UNIT_CREATED_BY_SPELL = 167;
    public static final int UNIT_NPC_FLAGS = 168;
    public static final int UNIT_NPC_EMOTESTATE = 169;
    public static final int UNIT_TRAINING_POINTS = 170;
    public static final int UNIT_FIELD_STAT0 = 171;
    public static final int UNIT_FIELD_STAT1 = 172;
    public static final int UNIT_FIELD_STAT2 = 173;
    public static final int UNIT_FIELD_STAT3 = 174;
    public static final int UNIT_FIELD_STAT4 = 175;
    public static final int UNIT_FIELD_POSSTAT0 = 176;
    public static final int UNIT_FIELD_POSSTAT1 = 177;
    public static final int UNIT_FIELD_POSSTAT2 = 178;
    public static final int UNIT_FIELD_POSSTAT3 = 179;
    public static final int UNIT_FIELD_POSSTAT4 = 180;
    public static final int UNIT_FIELD_NEGSTAT0 = 181;
    public static final int UNIT_FIELD_NEGSTAT1 = 182;
    public static final int UNIT_FIELD_NEGSTAT2 = 183;
    public static final int UNIT_FIELD_NEGSTAT3 = 184;
    public static final int UNIT_FIELD_NEGSTAT4 = 185;
    public static final int UNIT_FIELD_RESISTANCES = 186;
    public static final int UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE = 193;
    public static final int UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE = 200;
    public static final int UNIT_FIELD_BASE_MANA = 207;
    public static final int UNIT_FIELD_BASE_HEALTH = 208;
    public static final int UNIT_FIELD_BYTES_2 = 209;
    public static final int UNIT_FIELD_ATTACK_POWER = 210;
    public static final int UNIT_FIELD_ATTACK_POWER_MODS = 211;
    public static final int UNIT_FIELD_ATTACK_POWER_MULTIPLIER = 212;
    public static final int UNIT_FIELD_RANGED_ATTACK_POWER = 213;
    public static final int UNIT_FIELD_RANGED_ATTACK_POWER_MODS = 214;
    public static final int UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER = 215;
    public static final int UNIT_FIELD_MINRANGEDDAMAGE = 216;
    public static final int UNIT_FIELD_MAXRANGEDDAMAGE = 217;
    public static final int UNIT_FIELD_POWER_COST_MODIFIER = 218;
    public static final int UNIT_FIELD_POWER_COST_MULTIPLIER = 225;
    public static final int UNIT_FIELD_MAXHEALTHMODIFIER = 232;
    public static final int UNIT_FIELD_PADDING = 233;
    public static final int PLAYER_DUEL_ARBITER = 234;
    public static final int PLAYER_FLAGS = 236;
    public static final int PLAYER_GUILDID = 237;
    public static final int PLAYER_GUILDRANK = 238;
    public static final int PLAYER_BYTES = 239;
    public static final int PLAYER_BYTES_2 = 240;
    public static final int PLAYER_BYTES_3 = 241;
    public static final int PLAYER_DUEL_TEAM = 242;
    public static final int PLAYER_GUILD_TIMESTAMP = 243;
    public static final int PLAYER_QUEST_LOG_1_1 = 244;
    public static final int PLAYER_QUEST_LOG_1_2 = 245;
    public static final int PLAYER_QUEST_LOG_1_3 = 246;
    public static final int PLAYER_QUEST_LOG_1_4 = 247;
    public static final int PLAYER_QUEST_LOG_2_1 = 248;
    public static final int PLAYER_QUEST_LOG_2_2 = 249;
    public static final int PLAYER_QUEST_LOG_2_3 = 250;
    public static final int PLAYER_QUEST_LOG_2_4 = 251;
    public static final int PLAYER_QUEST_LOG_3_1 = 252;
    public static final int PLAYER_QUEST_LOG_3_2 = 253;
    public static final int PLAYER_QUEST_LOG_3_3 = 254;
    public static final int PLAYER_QUEST_LOG_3_4 = 255;
    public static final int PLAYER_QUEST_LOG_4_1 = 256;
    public static final int PLAYER_QUEST_LOG_4_2 = 257;
    public static final int PLAYER_QUEST_LOG_4_3 = 258;
    public static final int PLAYER_QUEST_LOG_4_4 = 259;
    public static final int PLAYER_QUEST_LOG_5_1 = 260;
    public static final int PLAYER_QUEST_LOG_5_2 = 261;
    public static final int PLAYER_QUEST_LOG_5_3 = 262;
    public static final int PLAYER_QUEST_LOG_5_4 = 263;
    public static final int PLAYER_QUEST_LOG_6_1 = 264;
    public static final int PLAYER_QUEST_LOG_6_2 = 265;
    public static final int PLAYER_QUEST_LOG_6_3 = 266;
    public static final int PLAYER_QUEST_LOG_6_4 = 267;
    public static final int PLAYER_QUEST_LOG_7_1 = 268;
    public static final int PLAYER_QUEST_LOG_7_2 = 269;
    public static final int PLAYER_QUEST_LOG_7_3 = 270;
    public static final int PLAYER_QUEST_LOG_7_4 = 271;
    public static final int PLAYER_QUEST_LOG_8_1 = 272;
    public static final int PLAYER_QUEST_LOG_8_2 = 273;
    public static final int PLAYER_QUEST_LOG_8_3 = 274;
    public static final int PLAYER_QUEST_LOG_8_4 = 275;
    public static final int PLAYER_QUEST_LOG_9_1 = 276;
    public static final int PLAYER_QUEST_LOG_9_2 = 277;
    public static final int PLAYER_QUEST_LOG_9_3 = 278;
    public static final int PLAYER_QUEST_LOG_9_4 = 279;
    public static final int PLAYER_QUEST_LOG_10_1 = 280;
    public static final int PLAYER_QUEST_LOG_10_2 = 281;
    public static final int PLAYER_QUEST_LOG_10_3 = 282;
    public static final int PLAYER_QUEST_LOG_10_4 = 283;
    public static final int PLAYER_QUEST_LOG_11_1 = 284;
    public static final int PLAYER_QUEST_LOG_11_2 = 285;
    public static final int PLAYER_QUEST_LOG_11_3 = 286;
    public static final int PLAYER_QUEST_LOG_11_4 = 287;
    public static final int PLAYER_QUEST_LOG_12_1 = 288;
    public static final int PLAYER_QUEST_LOG_12_2 = 289;
    public static final int PLAYER_QUEST_LOG_12_3 = 290;
    public static final int PLAYER_QUEST_LOG_12_4 = 291;
    public static final int PLAYER_QUEST_LOG_13_1 = 292;
    public static final int PLAYER_QUEST_LOG_13_2 = 293;
    public static final int PLAYER_QUEST_LOG_13_3 = 294;
    public static final int PLAYER_QUEST_LOG_13_4 = 295;
    public static final int PLAYER_QUEST_LOG_14_1 = 296;
    public static final int PLAYER_QUEST_LOG_14_2 = 297;
    public static final int PLAYER_QUEST_LOG_14_3 = 298;
    public static final int PLAYER_QUEST_LOG_14_4 = 299;
    public static final int PLAYER_QUEST_LOG_15_1 = 300;
    public static final int PLAYER_QUEST_LOG_15_2 = 301;
    public static final int PLAYER_QUEST_LOG_15_3 = 302;
    public static final int PLAYER_QUEST_LOG_15_4 = 303;
    public static final int PLAYER_QUEST_LOG_16_1 = 304;
    public static final int PLAYER_QUEST_LOG_16_2 = 305;
    public static final int PLAYER_QUEST_LOG_16_3 = 306;
    public static final int PLAYER_QUEST_LOG_16_4 = 307;
    public static final int PLAYER_QUEST_LOG_17_1 = 308;
    public static final int PLAYER_QUEST_LOG_17_2 = 309;
    public static final int PLAYER_QUEST_LOG_17_3 = 310;
    public static final int PLAYER_QUEST_LOG_17_4 = 311;
    public static final int PLAYER_QUEST_LOG_18_1 = 312;
    public static final int PLAYER_QUEST_LOG_18_2 = 313;
    public static final int PLAYER_QUEST_LOG_18_3 = 314;
    public static final int PLAYER_QUEST_LOG_18_4 = 315;
    public static final int PLAYER_QUEST_LOG_19_1 = 316;
    public static final int PLAYER_QUEST_LOG_19_2 = 317;
    public static final int PLAYER_QUEST_LOG_19_3 = 318;
    public static final int PLAYER_QUEST_LOG_19_4 = 319;
    public static final int PLAYER_QUEST_LOG_20_1 = 320;
    public static final int PLAYER_QUEST_LOG_20_2 = 321;
    public static final int PLAYER_QUEST_LOG_20_3 = 322;
    public static final int PLAYER_QUEST_LOG_20_4 = 323;
    public static final int PLAYER_QUEST_LOG_21_1 = 324;
    public static final int PLAYER_QUEST_LOG_21_2 = 325;
    public static final int PLAYER_QUEST_LOG_21_3 = 326;
    public static final int PLAYER_QUEST_LOG_21_4 = 327;
    public static final int PLAYER_QUEST_LOG_22_1 = 328;
    public static final int PLAYER_QUEST_LOG_22_2 = 329;
    public static final int PLAYER_QUEST_LOG_22_3 = 330;
    public static final int PLAYER_QUEST_LOG_22_4 = 331;
    public static final int PLAYER_QUEST_LOG_23_1 = 332;
    public static final int PLAYER_QUEST_LOG_23_2 = 333;
    public static final int PLAYER_QUEST_LOG_23_3 = 334;
    public static final int PLAYER_QUEST_LOG_23_4 = 335;
    public static final int PLAYER_QUEST_LOG_24_1 = 336;
    public static final int PLAYER_QUEST_LOG_24_2 = 337;
    public static final int PLAYER_QUEST_LOG_24_3 = 338;
    public static final int PLAYER_QUEST_LOG_24_4 = 339;
    public static final int PLAYER_QUEST_LOG_25_1 = 340;
    public static final int PLAYER_QUEST_LOG_25_2 = 341;
    public static final int PLAYER_QUEST_LOG_25_3 = 342;
    public static final int PLAYER_QUEST_LOG_25_4 = 343;
    public static final int PLAYER_VISIBLE_ITEM_1_CREATOR = 344;
    public static final int PLAYER_VISIBLE_ITEM_1_0 = 346;
    public static final int PLAYER_VISIBLE_ITEM_1_PROPERTIES = 358;
    public static final int PLAYER_VISIBLE_ITEM_1_PAD = 359;
    public static final int PLAYER_VISIBLE_ITEM_2_CREATOR = 360;
    public static final int PLAYER_VISIBLE_ITEM_2_0 = 362;
    public static final int PLAYER_VISIBLE_ITEM_2_PROPERTIES = 374;
    public static final int PLAYER_VISIBLE_ITEM_2_PAD = 375;
    public static final int PLAYER_VISIBLE_ITEM_3_CREATOR = 376;
    public static final int PLAYER_VISIBLE_ITEM_3_0 = 378;
    public static final int PLAYER_VISIBLE_ITEM_3_PROPERTIES = 390;
    public static final int PLAYER_VISIBLE_ITEM_3_PAD = 391;
    public static final int PLAYER_VISIBLE_ITEM_4_CREATOR = 392;
    public static final int PLAYER_VISIBLE_ITEM_4_0 = 394;
    public static final int PLAYER_VISIBLE_ITEM_4_PROPERTIES = 406;
    public static final int PLAYER_VISIBLE_ITEM_4_PAD = 407;
    public static final int PLAYER_VISIBLE_ITEM_5_CREATOR = 408;
    public static final int PLAYER_VISIBLE_ITEM_5_0 = 410;
    public static final int PLAYER_VISIBLE_ITEM_5_PROPERTIES = 422;
    public static final int PLAYER_VISIBLE_ITEM_5_PAD = 423;
    public static final int PLAYER_VISIBLE_ITEM_6_CREATOR = 424;
    public static final int PLAYER_VISIBLE_ITEM_6_0 = 426;
    public static final int PLAYER_VISIBLE_ITEM_6_PROPERTIES = 438;
    public static final int PLAYER_VISIBLE_ITEM_6_PAD = 439;
    public static final int PLAYER_VISIBLE_ITEM_7_CREATOR = 440;
    public static final int PLAYER_VISIBLE_ITEM_7_0 = 442;
    public static final int PLAYER_VISIBLE_ITEM_7_PROPERTIES = 454;
    public static final int PLAYER_VISIBLE_ITEM_7_PAD = 455;
    public static final int PLAYER_VISIBLE_ITEM_8_CREATOR = 456;
    public static final int PLAYER_VISIBLE_ITEM_8_0 = 458;
    public static final int PLAYER_VISIBLE_ITEM_8_PROPERTIES = 470;
    public static final int PLAYER_VISIBLE_ITEM_8_PAD = 471;
    public static final int PLAYER_VISIBLE_ITEM_9_CREATOR = 472;
    public static final int PLAYER_VISIBLE_ITEM_9_0 = 474;
    public static final int PLAYER_VISIBLE_ITEM_9_PROPERTIES = 486;
    public static final int PLAYER_VISIBLE_ITEM_9_PAD = 487;
    public static final int PLAYER_VISIBLE_ITEM_10_CREATOR = 488;
    public static final int PLAYER_VISIBLE_ITEM_10_0 = 490;
    public static final int PLAYER_VISIBLE_ITEM_10_PROPERTIES = 502;
    public static final int PLAYER_VISIBLE_ITEM_10_PAD = 503;
    public static final int PLAYER_VISIBLE_ITEM_11_CREATOR = 504;
    public static final int PLAYER_VISIBLE_ITEM_11_0 = 506;
    public static final int PLAYER_VISIBLE_ITEM_11_PROPERTIES = 518;
    public static final int PLAYER_VISIBLE_ITEM_11_PAD = 519;
    public static final int PLAYER_VISIBLE_ITEM_12_CREATOR = 520;
    public static final int PLAYER_VISIBLE_ITEM_12_0 = 522;
    public static final int PLAYER_VISIBLE_ITEM_12_PROPERTIES = 534;
    public static final int PLAYER_VISIBLE_ITEM_12_PAD = 535;
    public static final int PLAYER_VISIBLE_ITEM_13_CREATOR = 536;
    public static final int PLAYER_VISIBLE_ITEM_13_0 = 538;
    public static final int PLAYER_VISIBLE_ITEM_13_PROPERTIES = 550;
    public static final int PLAYER_VISIBLE_ITEM_13_PAD = 551;
    public static final int PLAYER_VISIBLE_ITEM_14_CREATOR = 552;
    public static final int PLAYER_VISIBLE_ITEM_14_0 = 554;
    public static final int PLAYER_VISIBLE_ITEM_14_PROPERTIES = 566;
    public static final int PLAYER_VISIBLE_ITEM_14_PAD = 567;
    public static final int PLAYER_VISIBLE_ITEM_15_CREATOR = 568;
    public static final int PLAYER_VISIBLE_ITEM_15_0 = 570;
    public static final int PLAYER_VISIBLE_ITEM_15_PROPERTIES = 582;
    public static final int PLAYER_VISIBLE_ITEM_15_PAD = 583;
    public static final int PLAYER_VISIBLE_ITEM_16_CREATOR = 584;
    public static final int PLAYER_VISIBLE_ITEM_16_0 = 586;
    public static final int PLAYER_VISIBLE_ITEM_16_PROPERTIES = 598;
    public static final int PLAYER_VISIBLE_ITEM_16_PAD = 599;
    public static final int PLAYER_VISIBLE_ITEM_17_CREATOR = 600;
    public static final int PLAYER_VISIBLE_ITEM_17_0 = 602;
    public static final int PLAYER_VISIBLE_ITEM_17_PROPERTIES = 614;
    public static final int PLAYER_VISIBLE_ITEM_17_PAD = 615;
    public static final int PLAYER_VISIBLE_ITEM_18_CREATOR = 616;
    public static final int PLAYER_VISIBLE_ITEM_18_0 = 618;
    public static final int PLAYER_VISIBLE_ITEM_18_PROPERTIES = 630;
    public static final int PLAYER_VISIBLE_ITEM_18_PAD = 631;
    public static final int PLAYER_VISIBLE_ITEM_19_CREATOR = 632;
    public static final int PLAYER_VISIBLE_ITEM_19_0 = 634;
    public static final int PLAYER_VISIBLE_ITEM_19_PROPERTIES = 646;
    public static final int PLAYER_VISIBLE_ITEM_19_PAD = 647;
    public static final int PLAYER_CHOSEN_TITLE = 648;
    public static final int PLAYER_FIELD_PAD_0 = 649;
    public static final int PLAYER_FIELD_INV_SLOT_HEAD = 650;
    public static final int PLAYER_FIELD_PACK_SLOT_1 = 696;
    public static final int PLAYER_FIELD_BANK_SLOT_1 = 728;
    public static final int PLAYER_FIELD_BANKBAG_SLOT_1 = 784;
    public static final int PLAYER_FIELD_VENDORBUYBACK_SLOT_1 = 798;
    public static final int PLAYER_FIELD_KEYRING_SLOT_1 = 822;
    public static final int PLAYER_FIELD_VANITYPET_SLOT_1 = 886;
    public static final int PLAYER_FARSIGHT = 922;
    public static final int PLAYER__FIELD_KNOWN_TITLES = 924;
    public static final int PLAYER_XP = 926;
    public static final int PLAYER_NEXT_LEVEL_XP = 927;
    public static final int PLAYER_SKILL_INFO_1_1 = 928;
    public static final int PLAYER_CHARACTER_POINTS1 = 1312;
    public static final int PLAYER_CHARACTER_POINTS2 = 1313;
    public static final int PLAYER_TRACK_CREATURES = 1314;
    public static final int PLAYER_TRACK_RESOURCES = 1315;
    public static final int PLAYER_BLOCK_PERCENTAGE = 1316;
    public static final int PLAYER_DODGE_PERCENTAGE = 1317;
    public static final int PLAYER_PARRY_PERCENTAGE = 1318;
    public static final int PLAYER_EXPERTISE = 1319;
    public static final int PLAYER_OFFHAND_EXPERTISE = 1320;
    public static final int PLAYER_CRIT_PERCENTAGE = 1321;
    public static final int PLAYER_RANGED_CRIT_PERCENTAGE = 1322;
    public static final int PLAYER_OFFHAND_CRIT_PERCENTAGE = 1323;
    public static final int PLAYER_SPELL_CRIT_PERCENTAGE1 = 1324;
    public static final int PLAYER_SHIELD_BLOCK = 1331;
    public static final int PLAYER_EXPLORED_ZONES_1 = 1332;
    public static final int PLAYER_REST_STATE_EXPERIENCE = 1460;
    public static final int PLAYER_FIELD_COINAGE = 1461;
    public static final int PLAYER_FIELD_MOD_DAMAGE_DONE_POS = 1462;
    public static final int PLAYER_FIELD_MOD_DAMAGE_DONE_NEG = 1469;
    public static final int PLAYER_FIELD_MOD_DAMAGE_DONE_PCT = 1476;
    public static final int PLAYER_FIELD_MOD_HEALING_DONE_POS = 1483;
    public static final int PLAYER_FIELD_MOD_TARGET_RESISTANCE = 1484;
    public static final int PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE = 1485;
    public static final int PLAYER_FIELD_BYTES = 1486;
    public static final int PLAYER_AMMO_ID = 1487;
    public static final int PLAYER_SELF_RES_SPELL = 1488;
    public static final int PLAYER_FIELD_PVP_MEDALS = 1489;
    public static final int PLAYER_FIELD_BUYBACK_PRICE_1 = 1490;
    public static final int PLAYER_FIELD_BUYBACK_TIMESTAMP_1 = 1502;
    public static final int PLAYER_FIELD_KILLS = 1514;
    public static final int PLAYER_FIELD_TODAY_CONTRIBUTION = 1515;
    public static final int PLAYER_FIELD_YESTERDAY_CONTRIBUTION = 1516;
    public static final int PLAYER_FIELD_LIFETIME_HONORABLE_KILLS = 1517;
    public static final int PLAYER_FIELD_BYTES2 = 1518;
    public static final int PLAYER_FIELD_WATCHED_FACTION_INDEX = 1519;
    public static final int PLAYER_FIELD_COMBAT_RATING_1 = 1520;
    public static final int PLAYER_FIELD_ARENA_TEAM_INFO_1_1 = 1544;
    public static final int PLAYER_FIELD_HONOR_CURRENCY = 1562;
    public static final int PLAYER_FIELD_ARENA_CURRENCY = 1563;
    public static final int PLAYER_FIELD_MOD_MANA_REGEN = 1564;
    public static final int PLAYER_FIELD_MOD_MANA_REGEN_INTERRUPT = 1565;
    public static final int PLAYER_FIELD_MAX_LEVEL = 1566;
    public static final int PLAYER_FIELD_DAILY_QUESTS_1 = 1567;
    public static final int OBJECT_FIELD_CREATED_BY = 6;
    public static final int GAMEOBJECT_DISPLAYID = 8;
    public static final int GAMEOBJECT_FLAGS = 9;
    public static final int GAMEOBJECT_ROTATION = 10;
    public static final int GAMEOBJECT_STATE = 14;
    public static final int GAMEOBJECT_POS_X = 15;
    public static final int GAMEOBJECT_POS_Y = 16;
    public static final int GAMEOBJECT_POS_Z = 17;
    public static final int GAMEOBJECT_FACING = 18;
    public static final int GAMEOBJECT_DYN_FLAGS = 19;
    public static final int GAMEOBJECT_FACTION = 20;
    public static final int GAMEOBJECT_TYPE_ID = 21;
    public static final int GAMEOBJECT_LEVEL = 22;
    public static final int GAMEOBJECT_ARTKIT = 23;
    public static final int GAMEOBJECT_ANIMPROGRESS = 24;
    public static final int GAMEOBJECT_PADDING = 25;
    public static final int DYNAMICOBJECT_CASTER = 6;
    public static final int DYNAMICOBJECT_BYTES = 8;
    public static final int DYNAMICOBJECT_SPELLID = 9;
    public static final int DYNAMICOBJECT_RADIUS = 10;
    public static final int DYNAMICOBJECT_POS_X = 11;
    public static final int DYNAMICOBJECT_POS_Y = 12;
    public static final int DYNAMICOBJECT_POS_Z = 13;
    public static final int DYNAMICOBJECT_FACING = 14;
    public static final int DYNAMICOBJECT_CASTTIME = 15;
    public static final int CORPSE_FIELD_OWNER = 6;
    public static final int CORPSE_FIELD_PARTY = 8;
    public static final int CORPSE_FIELD_FACING = 10;
    public static final int CORPSE_FIELD_POS_X = 11;
    public static final int CORPSE_FIELD_POS_Y = 12;
    public static final int CORPSE_FIELD_POS_Z = 13;
    public static final int CORPSE_FIELD_DISPLAY_ID = 14;
    public static final int CORPSE_FIELD_ITEM = 15;
    public static final int CORPSE_FIELD_BYTES_1 = 34;
    public static final int CORPSE_FIELD_BYTES_2 = 35;
    public static final int CORPSE_FIELD_GUILD = 36;
    public static final int CORPSE_FIELD_FLAGS = 37;
    public static final int CORPSE_FIELD_DYNAMIC_FLAGS = 38;
    public static final int CORPSE_FIELD_PAD = 39;

    public static int visibility(int offset) {
        if (offset >= PLAYER_SKILL_INFO_1_1 && offset < PLAYER_CHARACTER_POINTS1) {
            return PRIVATE;
        }
        return switch (offset) {
            case 0 -> PUBLIC;
            case 2 -> PUBLIC;
            case 3 -> PUBLIC;
            case 4 -> PUBLIC;
            case 5 -> 0;
            case 6 -> PUBLIC;
            case 8 -> PUBLIC;
            case 9 -> PUBLIC;
            case 10 -> PUBLIC;
            case 11 -> PUBLIC;
            case 12 -> PUBLIC;
            case 13 -> PUBLIC;
            case 14 -> PUBLIC;
            case 15 -> PUBLIC;
            case 16 -> PUBLIC;
            case 17 -> PUBLIC;
            case 18 -> PUBLIC;
            case 19 -> DYNAMIC;
            case 20 -> PUBLIC;
            case 21 -> PUBLIC;
            case 22 -> PUBLIC;
            case 23 -> PUBLIC;
            case 24 -> DYNAMIC;
            case 25 -> 0;
            case 26 -> PUBLIC;
            case 27 -> PUBLIC;
            case 28 -> DYNAMIC;
            case 29 -> PUBLIC;
            case 30 -> PUBLIC;
            case 31 -> PUBLIC;
            case 32 -> PUBLIC;
            case 33 -> PUBLIC;
            case 34 -> PUBLIC;
            case 35 -> PUBLIC;
            case 36 -> PUBLIC;
            case 37 -> PUBLIC;
            case 38 -> DYNAMIC;
            case 39 -> 0;
            case 40 -> PUBLIC;
            case 46 -> PUBLIC;
            case 47 -> PUBLIC;
            case 48 -> PUBLIC;
            case 55 -> PUBLIC;
            case 56 -> PUBLIC;
            case 57 -> OWNER_ONLY;
            case 58 -> OWNER_ONLY;
            case 59 -> OWNER_ONLY;
            case 60 -> PUBLIC;
            case 61 -> 0;
            case 62 -> PUBLIC;
            case 104 -> PUBLIC;
            case 118 -> PUBLIC;
            case 132 -> PUBLIC;
            case 146 -> PUBLIC;
            case 147 -> PUBLIC;
            case 149 -> PRIVATE;
            case 150 -> PUBLIC;
            case 151 -> PUBLIC;
            case 152 -> PUBLIC;
            case 153 -> PUBLIC;
            case 154 -> PUBLIC;
            case 155 -> PRIVATE | OWNER_ONLY;
            case 156 -> PRIVATE | OWNER_ONLY;
            case 157 -> PRIVATE | OWNER_ONLY;
            case 158 -> PRIVATE | OWNER_ONLY;
            case 159 -> PUBLIC;
            case 160 -> PUBLIC;
            case 161 -> PUBLIC;
            case 162 -> OWNER_ONLY;
            case 163 -> OWNER_ONLY;
            case 164 -> DYNAMIC;
            case 165 -> PUBLIC;
            case 166 -> PUBLIC;
            case 167 -> PUBLIC;
            case 168 -> DYNAMIC;
            case 169 -> PUBLIC;
            case 170 -> OWNER_ONLY;
            case 171 -> PRIVATE | OWNER_ONLY;
            case 172 -> PRIVATE | OWNER_ONLY;
            case 173 -> PRIVATE | OWNER_ONLY;
            case 174 -> PRIVATE | OWNER_ONLY;
            case 175 -> PRIVATE | OWNER_ONLY;
            case 176 -> PRIVATE | OWNER_ONLY;
            case 177 -> PRIVATE | OWNER_ONLY;
            case 178 -> PRIVATE | OWNER_ONLY;
            case 179 -> PRIVATE | OWNER_ONLY;
            case 180 -> PRIVATE | OWNER_ONLY;
            case 181 -> PRIVATE | OWNER_ONLY;
            case 182 -> PRIVATE | OWNER_ONLY;
            case 183 -> PRIVATE | OWNER_ONLY;
            case 184 -> PRIVATE | OWNER_ONLY;
            case 185 -> PRIVATE | OWNER_ONLY;
            case 186 -> PRIVATE | OWNER_ONLY;
            case 193 -> PRIVATE | OWNER_ONLY;
            case 200 -> PRIVATE | OWNER_ONLY;
            case 207 -> PUBLIC;
            case 208 -> PRIVATE | OWNER_ONLY;
            case 209 -> PUBLIC;
            case 210 -> PRIVATE | OWNER_ONLY;
            case 211 -> PRIVATE | OWNER_ONLY;
            case 212 -> PRIVATE | OWNER_ONLY;
            case 213 -> PRIVATE | OWNER_ONLY;
            case 214 -> PRIVATE | OWNER_ONLY;
            case 215 -> PRIVATE | OWNER_ONLY;
            case 216 -> PRIVATE | OWNER_ONLY;
            case 217 -> PRIVATE | OWNER_ONLY;
            case 218 -> PRIVATE | OWNER_ONLY;
            case 225 -> PRIVATE | OWNER_ONLY;
            case 232 -> PRIVATE | OWNER_ONLY;
            case 233 -> 0;
            case 234 -> PUBLIC;
            case 236 -> PUBLIC;
            case 237 -> PUBLIC;
            case 238 -> PUBLIC;
            case 239 -> PUBLIC;
            case 240 -> PUBLIC;
            case 241 -> PUBLIC;
            case 242 -> PUBLIC;
            case 243 -> PUBLIC;
            case 244 -> GROUP_ONLY;
            case 245 -> PRIVATE;
            case 246 -> PRIVATE;
            case 247 -> PRIVATE;
            case 248 -> GROUP_ONLY;
            case 249 -> PRIVATE;
            case 250 -> PRIVATE;
            case 251 -> PRIVATE;
            case 252 -> GROUP_ONLY;
            case 253 -> PRIVATE;
            case 254 -> PRIVATE;
            case 255 -> PRIVATE;
            case 256 -> GROUP_ONLY;
            case 257 -> PRIVATE;
            case 258 -> PRIVATE;
            case 259 -> PRIVATE;
            case 260 -> GROUP_ONLY;
            case 261 -> PRIVATE;
            case 262 -> PRIVATE;
            case 263 -> PRIVATE;
            case 264 -> GROUP_ONLY;
            case 265 -> PRIVATE;
            case 266 -> PRIVATE;
            case 267 -> PRIVATE;
            case 268 -> GROUP_ONLY;
            case 269 -> PRIVATE;
            case 270 -> PRIVATE;
            case 271 -> PRIVATE;
            case 272 -> GROUP_ONLY;
            case 273 -> PRIVATE;
            case 274 -> PRIVATE;
            case 275 -> PRIVATE;
            case 276 -> GROUP_ONLY;
            case 277 -> PRIVATE;
            case 278 -> PRIVATE;
            case 279 -> PRIVATE;
            case 280 -> GROUP_ONLY;
            case 281 -> PRIVATE;
            case 282 -> PRIVATE;
            case 283 -> PRIVATE;
            case 284 -> GROUP_ONLY;
            case 285 -> PRIVATE;
            case 286 -> PRIVATE;
            case 287 -> PRIVATE;
            case 288 -> GROUP_ONLY;
            case 289 -> PRIVATE;
            case 290 -> PRIVATE;
            case 291 -> PRIVATE;
            case 292 -> GROUP_ONLY;
            case 293 -> PRIVATE;
            case 294 -> PRIVATE;
            case 295 -> PRIVATE;
            case 296 -> GROUP_ONLY;
            case 297 -> PRIVATE;
            case 298 -> PRIVATE;
            case 299 -> PRIVATE;
            case 300 -> GROUP_ONLY;
            case 301 -> PRIVATE;
            case 302 -> PRIVATE;
            case 303 -> PRIVATE;
            case 304 -> GROUP_ONLY;
            case 305 -> PRIVATE;
            case 306 -> PRIVATE;
            case 307 -> PRIVATE;
            case 308 -> GROUP_ONLY;
            case 309 -> PRIVATE;
            case 310 -> PRIVATE;
            case 311 -> PRIVATE;
            case 312 -> GROUP_ONLY;
            case 313 -> PRIVATE;
            case 314 -> PRIVATE;
            case 315 -> PRIVATE;
            case 316 -> GROUP_ONLY;
            case 317 -> PRIVATE;
            case 318 -> PRIVATE;
            case 319 -> PRIVATE;
            case 320 -> GROUP_ONLY;
            case 321 -> PRIVATE;
            case 322 -> PRIVATE;
            case 323 -> PRIVATE;
            case 324 -> GROUP_ONLY;
            case 325 -> PRIVATE;
            case 326 -> PRIVATE;
            case 327 -> PRIVATE;
            case 328 -> GROUP_ONLY;
            case 329 -> PRIVATE;
            case 330 -> PRIVATE;
            case 331 -> PRIVATE;
            case 332 -> GROUP_ONLY;
            case 333 -> PRIVATE;
            case 334 -> PRIVATE;
            case 335 -> PRIVATE;
            case 336 -> GROUP_ONLY;
            case 337 -> PRIVATE;
            case 338 -> PRIVATE;
            case 339 -> PRIVATE;
            case 340 -> GROUP_ONLY;
            case 341 -> PRIVATE;
            case 342 -> PRIVATE;
            case 343 -> PRIVATE;
            case 344 -> PUBLIC;
            case 346 -> PUBLIC;
            case 358 -> PUBLIC;
            case 359 -> PUBLIC;
            case 360 -> PUBLIC;
            case 362 -> PUBLIC;
            case 374 -> PUBLIC;
            case 375 -> PUBLIC;
            case 376 -> PUBLIC;
            case 378 -> PUBLIC;
            case 390 -> PUBLIC;
            case 391 -> PUBLIC;
            case 392 -> PUBLIC;
            case 394 -> PUBLIC;
            case 406 -> PUBLIC;
            case 407 -> PUBLIC;
            case 408 -> PUBLIC;
            case 410 -> PUBLIC;
            case 422 -> PUBLIC;
            case 423 -> PUBLIC;
            case 424 -> PUBLIC;
            case 426 -> PUBLIC;
            case 438 -> PUBLIC;
            case 439 -> PUBLIC;
            case 440 -> PUBLIC;
            case 442 -> PUBLIC;
            case 454 -> PUBLIC;
            case 455 -> PUBLIC;
            case 456 -> PUBLIC;
            case 458 -> PUBLIC;
            case 470 -> PUBLIC;
            case 471 -> PUBLIC;
            case 472 -> PUBLIC;
            case 474 -> PUBLIC;
            case 486 -> PUBLIC;
            case 487 -> PUBLIC;
            case 488 -> PUBLIC;
            case 490 -> PUBLIC;
            case 502 -> PUBLIC;
            case 503 -> PUBLIC;
            case 504 -> PUBLIC;
            case 506 -> PUBLIC;
            case 518 -> PUBLIC;
            case 519 -> PUBLIC;
            case 520 -> PUBLIC;
            case 522 -> PUBLIC;
            case 534 -> PUBLIC;
            case 535 -> PUBLIC;
            case 536 -> PUBLIC;
            case 538 -> PUBLIC;
            case 550 -> PUBLIC;
            case 551 -> PUBLIC;
            case 552 -> PUBLIC;
            case 554 -> PUBLIC;
            case 566 -> PUBLIC;
            case 567 -> PUBLIC;
            case 568 -> PUBLIC;
            case 570 -> PUBLIC;
            case 582 -> PUBLIC;
            case 583 -> PUBLIC;
            case 584 -> PUBLIC;
            case 586 -> PUBLIC;
            case 598 -> PUBLIC;
            case 599 -> PUBLIC;
            case 600 -> PUBLIC;
            case 602 -> PUBLIC;
            case 614 -> PUBLIC;
            case 615 -> PUBLIC;
            case 616 -> PUBLIC;
            case 618 -> PUBLIC;
            case 630 -> PUBLIC;
            case 631 -> PUBLIC;
            case 632 -> PUBLIC;
            case 634 -> PUBLIC;
            case 646 -> PUBLIC;
            case 647 -> PUBLIC;
            case 648 -> PUBLIC;
            case 649 -> 0;
            case 650 -> PRIVATE;
            case 696 -> PRIVATE;
            case 728 -> PRIVATE;
            case 784 -> PRIVATE;
            case 798 -> PRIVATE;
            case 822 -> PRIVATE;
            case 886 -> PRIVATE;
            case 922 -> PRIVATE;
            case 924 -> PRIVATE;
            case 926 -> PRIVATE;
            case 927 -> PRIVATE;
            case 928 -> PRIVATE;
            case 1312 -> PRIVATE;
            case 1313 -> PRIVATE;
            case 1314 -> PRIVATE;
            case 1315 -> PRIVATE;
            case 1316 -> PRIVATE;
            case 1317 -> PRIVATE;
            case 1318 -> PRIVATE;
            case 1319 -> PRIVATE;
            case 1320 -> PRIVATE;
            case 1321 -> PRIVATE;
            case 1322 -> PRIVATE;
            case 1323 -> PRIVATE;
            case 1324 -> PRIVATE;
            case 1331 -> PRIVATE;
            case 1332 -> PRIVATE;
            case 1460 -> PRIVATE;
            case 1461 -> PRIVATE;
            case 1462 -> PRIVATE;
            case 1469 -> PRIVATE;
            case 1476 -> PRIVATE;
            case 1483 -> PRIVATE;
            case 1484 -> PRIVATE;
            case 1485 -> PRIVATE;
            case 1486 -> PRIVATE;
            case 1487 -> PRIVATE;
            case 1488 -> PRIVATE;
            case 1489 -> PRIVATE;
            case 1490 -> PRIVATE;
            case 1502 -> PRIVATE;
            case 1514 -> PRIVATE;
            case 1515 -> PRIVATE;
            case 1516 -> PRIVATE;
            case 1517 -> PRIVATE;
            case 1518 -> PRIVATE;
            case 1519 -> PRIVATE;
            case 1520 -> PRIVATE;
            case 1544 -> PRIVATE;
            case 1562 -> PRIVATE;
            case 1563 -> PRIVATE;
            case 1564 -> PRIVATE;
            case 1565 -> PRIVATE;
            case 1566 -> PRIVATE;
            case 1567 -> PRIVATE;
            default -> PUBLIC;
        };
    }
}
